apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  namespace: dev
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
